# Use the official Ubuntu base image
FROM ubuntu:latest

# Set the maintainer or author of this Dockerfile
LABEL maintainer="yourname@example.com"

# Update the package list
RUN apt-get update

# Install nano text editor
RUN apt-get install -y nano

# Set the default command for the container
CMD ["/bin/bash"]
